# Generated by Django 4.2 on 2024-02-24 18:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('question', models.CharField()),
                ('mode', models.CharField(choices=[('pribadi', 'Pribadi'), ('pengawasan', 'Pengawasan')], default='pribadi', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
