# Generated by Django 4.2 on 2024-03-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='causes',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
