# Generated by Django 4.2 on 2024-02-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='mode',
            field=models.CharField(choices=[('PRIBADI', 'pribadi'), ('PENGAWASAN', 'pengawasan')], default='PRIBADI', max_length=20),
        ),
    ]
