# Generated by Django 4.2 on 2024-02-27 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0003_question_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
