# Generated by Django 4.2 on 2024-05-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0004_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='causes',
            name='root_status',
            field=models.BooleanField(default=False),
        ),
    ]
